### ISSUE TITLE
Cranium Cafe should serve coffee

### ISSUE THREAD

**Issue by tlt-Jon** [craniumcafe/issue-tracker#156]
I am wanting the Cranium Cafe to actually serve coffee (or hot chocolate). I know that this will be a bit of a challenge. Robotic arms can be expensive (see image) and are notoriously averse to liquid substances.

![31eccsyuewl](https://user-images.githubusercontent.com/4442049/30173767-102d936a-93b6-11e7-89d8-daced3c84160.jpg)

[## **PRICE: $1,399.00**
](https://www.amazon.com/Dobot-Magician-Advanced-Educational-Version/dp/B01N3SFOHT/ref=sr_1_3?ie=UTF8&qid=1504801080&sr=8-3&keywords=robotic+arm)

However, for a product called "Cranium Cafe" I would expect no less.

Jon

**Comment by tlt-Jon** [comment]
Nice that you can leave comments

**Comment by tlt-Jon** [comment]
And that comments can have pictures.
![31eccsyuewl](https://user-images.githubusercontent.com/4442049/30179545-009741bc-93ca-11e7-9b40-1b8c6be3ec6d.jpg)

**Comment by tdiven** [comment]
LOL! I would love to have a hot cup of coffee served everytime I get into a Cranium Cafe meeting!

**Comment by tlt-Jon** [comment]
ohmygosh! a HOT cup of coffee was my next request!  :)
