### ISSUE TITLE
Students can only invite other students for meetings

### ISSUE THREAD

**Issue by SethEJensen** [craniumcafe/issue-tracker#180]
In the Schedule Cafe Meeting window under the Cranium Cafe Tab students can invite councilors to the meetings they create their and it can confuse councilors to thinking they are double booked. Solution would to make it so their is an option for the integration to make it so students can only invite other students to the meeting they create.

**Comment by mikeg0** [comment]
Is this fixed now?

**Comment by SethEJensen** [comment]
yes, and ive gotten no complaints on it


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
