### ISSUE TITLE
Group Lobby Message

### ISSUE THREAD

**Issue by adestesipin** [craniumcafe/issue-tracker#190]
**If you are reporting an issue, please fill out the following sections and tag this with the "issue" label**:

**What steps will reproduce the problem?**

1. Open up Appointment Manager
2.  Open up settings in Appointment Manager
3.  Type in a group lobby message
4. Click on save

**What is the expected result?**
The expected result is that the group lobby message will save.  The group lobby message will be viewable when students are waiting in the group lobby.

**What happens instead?**
The group lobby message doesn't save after hitting save.  The group lobby message says  Welcome to the Cranium Cafe Lobby!
The meeting's organizer will be with you shortly. Please keep this window open so you can be added to the video meeting room when it's your turn. While you are in the Lobby, please feel free to chat with others within this group chat area. 

**Browsers tested**
Firefox, Chrome

**Comment by mikeg0** [comment]
fixed mid-Oct 2017
