### ISSUE TITLE
Login confusion with accounts having the same email

### ISSUE THREAD

**Issue by SethEJensen** [craniumcafe/issue-tracker#209]
for OEI trainees there is a lot of confusion when they try to login using their email address to cranium cafe if they have two accounts with the same email it defaults to the one they last logged in with.
Planned solution is to offer a list of accounts sharing that email address for the user to select from when they try to login.

**Comment by mikeg0** [comment]
You'd have to add logic to validate the password for any email account that matches the one entered.
They may have an account w/ same email in 5 instances.

Find at least one account that works with that password.  If password validates for one, popup a box asking to select an integration . Upon selection, prompt again for that integration's password.


Please style the integration selection like this dialog ...
![image](https://user-images.githubusercontent.com/1077290/31561449-2838be64-b015-11e7-9d9c-6b1c9fdbd729.png)

**Comment by SethEJensen** [comment]
Issue has been solved with user account select on login
