### ISSUE TITLE
Outlook Connector Feedback

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#219]
The University of Utah has provided the following feedback regarding the Outlook Connector.

1. Cranium Café-entered appointments must be edited and deleted in Cranium Café—if they are deleted in Outlook, they reappear the next time someone refreshes the page or syncs.
2. Outlook-entered appointments must be edited and deleted in Outlook—they cannot be deleted or edited in Cranium Café.
3. Only the subject and time is visible in Cranium Café for Outlook events. 
4. “Synchronizing” is misspelled as “Synchonizing” on the notification window for the plugin.
5. If a user enters availability into Cranium Café and syncs with Outlook, and then in Outlook copies and pastes the availability into a new slot and syncs, the availability will not show up in Cranium Café. 
6. The calendar in Cranium Café can be difficult to read: events that occur at the same time or in consecutive time blocks (i.e., 8-8:30, 8:30-9) overlap or cut each other off.
7. The reason codes selected in a block of availability in Cranium Café do not show up in Outlook. Would it be possible to see reason codes in the synced block in Outlook?
8. When deleting Outlook-made events from Outlook, the user must sync with Cranium Café and then refresh their Cranium Café calendar to see the change.
9. Outlook timeblocks and Cranium Café timeblocks overlap with each other on the Cranium Cafe calendar instead of sitting adjacent to each other. This makes it impossible to delete or edit a timeblock in one interface without first deleting or removing the conflicting timeblock in the other. This is a big problem.
10. Events marked as "private" on a user's Outlook calendar sync with full details to Cranium Cafe.

**Comment by heatherconexed** [comment]
Hi Seth, have you had a chance to review?  Do you have any updates and will we be able to make adjustments for some of the items that are a larger issue?  Thanks!

For example, Outlook timeblocks and Cranium Café timeblocks overlap with each other on the Cranium Cafe calendar instead of sitting adjacent to each other. This makes it impossible to delete or edit a timeblock in one interface without first deleting or removing the conflicting timeblock in the other. This is a big problem.

**Comment by mikeg0** [comment]
#1,#4,#8,#10 are fixed in next release
#2 won't fix - outlook created events should be edited in their proper interface
#3 possible v2 fix - outlook events should be viewed and managed from outlook
#5 possible v2 fix - office hours can only be managed from webUI only
#6,#7,#9, #11 can fix - haven't found the time to rework the UI

**Comment by tdiven** [comment]
#5 - This request should be at the top of the list. They would like to edit Cranium Cafe office hours from Outlook.

**Comment by mikeg0** [comment]
#5 is in progress on the development list targeted for Feb 2018.  It is a complicated issue as we'll need UI elements and REST API calls designed for use from within Outlook.

**Comment by mikeg0** [comment]
#9 and #6 are fixed

**Comment by mikeg0** [comment]
#7 is fixed.

Closing this issue.  Please open separate issues if any of the above have problems.
