### ISSUE TITLE
Admin Panel - Reason Codes Category table - sort by title

### ISSUE THREAD

**Issue by SethEJensen** [craniumcafe/issue-tracker#222]
Corina Marshall has requested that we allow the reason codes category table in the admin panel to be sort-able by title.

**Comment by mikeg0** [comment]
should be relatively easy to use datatables for the category listing.  

This is for https://admin.craniumcafe.com/reasoncodes , right?  

![image](https://user-images.githubusercontent.com/1077290/34268381-b5f716f2-e63d-11e7-9a36-3cdf96af5108.png)
