### ISSUE TITLE
UofU Unsecure Connection Error

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#224]
Ticket #60351: Unsecure Connection

NATHAN C SANDERS, Dec     6, 12:45 PM MST:     

Hi Heather,    
     
When I try and schedule a meeting from a cafe card, I click the U login button and I get a pop up about an unsecured connection. I've attached a screenshot.  

![screen shot 2017-12-06 at 12 40 43 pm](https://user-images.githubusercontent.com/33461356/33684189-a9f74f52-da8a-11e7-917f-d3c83b5e0f2b.png)
Thanks
Nate

**Comment by heatherconexed** [comment]
From: Seth Jensen [mailto:seth@conexed.com] 
Sent: Wednesday, December 6, 2017 1:37 PM
To: heather@conexed.com
Cc: Michael Gorham <michael@conexed.com>
Subject: Re: FW: Unsecure Connection

it looks like he might need to check his computers time to make sure it isnt off.

**Comment by mikeg0** [comment]
Nathan was using the CAS login type.  CAS is no longer supported by UofU.
