### ISSUE TITLE
Code Implementation Guide link is 'broken'

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#225]
Hi Seth – 
 
We talked about this last week (or the week before).  In the Group Card tab, when you click on the Embed Widget, under the code there is “For help implementing this code, please see our Code Implementation Guide” 
 
This link takes you to https://www.zendesk.com/help-center-closed?utm_source=helpcenter-closed&utm_medium=poweredbyzendesk&utm_campaign=text&utm_content=craniumcafe.zendesk.com, which gives the error,
![code implementation guide](https://user-images.githubusercontent.com/33461356/33686850-7054e10c-da93-11e7-9093-c71b09325d0c.jpg)

**Comment by heatherconexed** [comment]
From: Seth Jensen [mailto:seth@conexed.com] 
Sent: Wednesday, December 6, 2017 2:21 PM
To: heather@conexed.com
Subject: Re: FW: Code Implementation Guide Link Broken

Heather,
Fixing the link will be easy I just dont know if we have anything to replace that, You can tell Nate if he asks that this will be fixed during their christmas break

**Comment by mikeg0** [comment]
@tdiven we need the link for the embed cafe widget help

**Comment by heatherconexed** [comment]
Notified UofU of this update.
