### ISSUE TITLE
Student Lookup (ability to view more than 10)

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#227]
NATHAN C SANDERS, Dec 12, 9:47 AM MST:
Hi Heather,

Under student lookup, when I look up my name for example (Sanders) I can see 27 results but there is no next button to see past the first 10. I know we have talked about this but not sure we sent an official ticket.

thanks,

Nate
Attachment(s)
Screen Shot 2017-12-12 at 9.45.45 AM.png

**Comment by heatherconexed** [comment]
From: heather@conexed.com [mailto:heather@conexed.com] 
Sent: Tuesday, December 12, 2017 9:54 AM
To: 'Michael Gorham' <michael@conexed.com>; seth@conexed.com
Subject: FW: Student Lookup

Hi Michael – 

Please see screen shot below.  The Student Lookup currently shows 10 entries, but there’s no option to show additional (next page, etc) if there are more than 10 entries.  I’ll add this to our spreadsheet.
![student lookup capture](https://user-images.githubusercontent.com/33461356/33897941-1a3dab42-df24-11e7-87ce-eab32161c65a.png)

**Comment by mikeg0** [comment]
This is fixed now - pagination now shows at bottom right of table.
