### ISSUE TITLE
LBCC - Students entering Cafe from Knock on Door are not showing on historicals

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#228]
From: Javier Villasenor [mailto:jvillasenor@lbcc.edu] 
Sent: Tuesday, December 12, 2017 9:33 AM
To: Judy Oh <joh@lbcc.edu>; heather@conexed.com
Cc: Ralph Meza <rmeza@lbcc.edu>; Jessica Hurtado (jhurtado@ccconlineed.org) <jhurtado@ccconlineed.org>; Marilyn Harvey <mharvey@ccconlineed.org>; 'Tracy Gorham' <tracy@conexed.com>; seth@conexed.com
Subject: RE: Chat sessions

Hi Heather,

I wanted to see if you were able to look up the issue that Judy Oh had.  I had online counseling and had the same thing happen to me.  

For example, using the Administrative settings I took snap shots of Meetings, Users, Chats along with the Appointment Manager.  Under the Users  for December 1th you see Patrick Ramirez logged in as a walk in session.   He is also on the Chat.  However, He does not show up on the Video meeting and on the Appointment Manager Calendar as a seen video meeting.

This is important because we need to capture the numbers.  In addition, we need to add notes to our session.  

Can you please provide me some feedback  on how we can fix this issue.

Thank you,

Best,
Javier
![lbcc2](https://user-images.githubusercontent.com/33461356/33898398-84481ddc-df25-11e7-9112-f604433b9c41.JPG)
![lbcc3](https://user-images.githubusercontent.com/33461356/33898400-848aaef4-df25-11e7-9c69-951fe9300ce0.JPG)
![lbcc4](https://user-images.githubusercontent.com/33461356/33898401-84a23632-df25-11e7-8bfd-df1893734629.JPG)
![lbcc1](https://user-images.githubusercontent.com/33461356/33898402-84bb0efa-df25-11e7-8465-552307435fe9.JPG)

**Comment by mikeg0** [comment]
Status Update:  the records are definitely being stored in the database, but just not pulled correctly.  Looks like Javier was in a scheduled cafe meeting with Student A, Patrick Ramirez joined his lobby 10 minutes into the scheduled meeting, then Javier let Patrick Ramirez into his scheduled meeting after Student A left.  A perfectly normal use case.  

Currently updating the reports to show this use case.  Should have a fix out by end of day.

**Comment by mikeg0** [comment]
The problem lies in the fact that Javier was technically in a single meeting, but the reports should be split into two meeting sessions.  The only way to really identify these type of multiple session meetings is by looking at each attendee's start_time and end_time values.

![image](https://user-images.githubusercontent.com/1077290/34276192-9439780a-e65d-11e7-9995-5ceb5adc8488.png)
