### ISSUE TITLE
Crafton Hills - End of Meeting Survey (Counseling Group)

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#234]
Hi Seth - 

I've created this task to track the review and progress of Crafton Hill's "knock on door" and end of meeting survey concerns associated with their Counseling group.

After review yesterday you mentioned that the "knock on door" is not looking at the group and the end of meeting survey is erring out.

Please let me know if you'd like me to complete additional tests.

Thanks!

**Comment by mikeg0** [comment]
this should be fixed now.  closing.
