### ISSUE TITLE
In-Office appointment scheduled when this was not an option

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#235]
Seth -

Any ideas on how this happened?  This seemed similar to LA Pierce’s issue a few weeks ago.  They did not have in-office meetings in their office hours, but the student was able to schedule.  We were unable to replicate and it hasn’t been an issue since.

I was unable to replicate for Nadine (UC Berkeley's Earth & Planetary Science).

---------------------------

From: Nadine Spingola-Hutton [mailto:nspingola@berkeley.edu] 
Sent: Thursday, December 21, 2017 9:55 AM
To: heather@conexed.com; Seth Jensen <Seth@conexed.com>
Subject: Student was able to make an "In Office" meeting when it's not an option

Hi Heather and Seth,

This student scheduled an "In Office" meeting with me today at 11am PST, but I only have it setup to do video or phone meeting (see print screen). I also logged in as a student and only see telephone and video as options (attached print screen) I emailed her right away and she responded with a print screen that also shows telephone and video so I'm very confused!

Best,
Nadine

My appointment calendar: 
![uc berkeley 12 21](https://user-images.githubusercontent.com/33461356/34313633-c753c39a-e729-11e7-8aa5-4ae7f1dde437.jpg)

What I see as a student:
![uc berkeley 12 21 a](https://user-images.githubusercontent.com/33461356/34313648-e4b5bba0-e729-11e7-97f1-7e14cb507c4e.jpg)

What Cynthia sent me:
![uc berkeley 12 21 b](https://user-images.githubusercontent.com/33461356/34313668-013296ae-e72a-11e7-9a41-09265568aa1a.png)

**Comment by mikeg0** [comment]
This should be fixed from our latest patch.  Please re-open if not.
