### ISSUE TITLE
Error when copying/pasting to Whiteboard

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#237]
I've attached three videos Kaplan made when copying/pasting to the Whiteboard.  It shows code and does not paste properly, or does not wrap and is a continued string.  Please take a look.

1. Copy/Paste Firefox - Mac
https://drive.google.com/file/d/1fpgooVSWY6oVJxp-L4p4RyuSMuLgqo4M/view

2. Copy/Paste Chome - Mac
https://drive.google.com/file/d/1XnFc3X902Ydux4ovzHC9bGHdLVCzm9ON/view

3. Word wrap Chrome - Mac
https://drive.google.com/file/d/1rkSp0M2MzRG598hz2Ba7zgZfTg3YX6zQ/view

I was able to replicate all instances.  

Thanks,
Heather

**Comment by mikeg0** [comment]
![image](https://user-images.githubusercontent.com/1077290/34268184-022c3152-e63d-11e7-859e-6ad7093140e9.png)

**Comment by mikeg0** [comment]
fixed
