### ISSUE TITLE
UofU - Email Meeting Notification Update

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#243]
Per Mike's meeting with Cory on 1/3/18, the UofU would like to update the meeting email notification as follows:

1) From: to be changed from Cranium Cafe to, either the person (e.g. Cory) or the institution (e.g. the U)
2) The subject line order changed to: Person, Place, and then ConexED Appointment Confirmation
3) The order of the message, beginning Hi Jane Doe, and the U of U branding to be switched: message first - followed by branding.
4) Everything below the iCal feed to be deleted.

**Comment by mikeg0** [comment]
This should be fixed now.  Post here if they want other updates or if it's other than what they want.
