### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#249]
I created this task as a placeholder for all feature requests (both client and internal).

* We have "cancel" function in the email meeting notification, add "reschedule" function.
* Add "reschedule" function within the My Appointments page, in lieu of cancelling and creating a new event.
* UofU (Katie Barnard) requested that we add a time buffer for all meetings.  For example, a student schedules an appt. from 2:00-2:30, the next appointment window would begin at 2:45.
 * Update Chat and Meeting archives in Admin panel to match user information (username, full name, or both).
* Using the Archive view in the User panel, give ConexED roles access to view all users and not just their archives. 
* Alphabetize the list of school instances (drop down menu in Admin panel).
* System Notification (in upper right hand corner of User Panel, alerting all users of updates to the platform.

**Comment by mikeg0** [comment]
What was the "Front desk lobby access" request?  Was it the ability for front desk agents to see who's in the group lobby?

**Comment by heatherconexed** [comment]
What was the "Front desk lobby access" request? Was it the ability for front desk agents to see who's in the group lobby?
[Heather] Yes, the ability for the front desk to see who is in the lobby, and communicate with them via chat only (providing updates on wait, etc)

**Comment by heatherconexed** [comment]
Marking as complete and adding each request as a new ticket.
