### ISSUE TITLE
LocationId not passed consistently

### ISSUE THREAD

**Issue by mikeg0** [craniumcafe/issue-tracker#255]
LocationId is sometimes not passed through to appointment scheduling.

Code is located here ... need to investigate how this can happen.
https://github.com/craniumcafe/group-scheduler/blob/b67ed558fa58accd41937067a59d9af94b12e98a/src/client/components/AvailableTimes.jsx#L58-L68

**Comment by SethEJensen** [comment]
found and fixed issue
