### ISSUE TITLE
Saddleback College - Multiple Logins for ConexED

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#276]
This is a follow up to our on-campus meeting with Saddleback College on 1/11.

Kim showed us the multiple login points she has to go through to schedule a meeting with a tutor through ConexED.

First Login, Canvas
Second Login, ConexED (via a link in Canvas (look at updating this as an iframe until the new LTI is complete))
Third Login, ConexED (when selecting "schedule a meeting" or "knock on door")

**Comment by mikeg0** [comment]
This should be fixed now.  Please test.

**Comment by heatherconexed** [comment]
I emailed Kim this morning asking her to test and confirm that this has been resolved.
I asked Kim if I could be added to the TU300 course in Canvas to test as well and help look at iframe options per our on-campus meeting.

**Comment by heatherconexed** [comment]
Kim D'Arcy confirmed that the number of logins has been reduced to two.

1.	Canvas
2.	ConexEd – via Canvas
