### ISSUE TITLE
Feature Request - Ability to see which groups users are assigned to

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#286]
Add an option (either in Admin or User panel) to be able to quickly see which group(s) a particular user is assigned to.  This is a request that would be especially helpful for the UofU where they have so many Departments and Groups created, and would allow us to help troubleshoot issues easily.

**Comment by mikeg0** [comment]
Added to admin user edit view

Example:
https://admin.craniumcafe.com/users/view/16649
