### ISSUE TITLE
Allison Musser Outlook Calendar 

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#296]
Per our meeting with the UofU Career Center 1/17.

Allison’s Outlook calendar is a bit messy – showing ONE block for the student appointment, ONE block for the student appointment notes and ONE block for office hours.  

**Per Allison 1/18/18 - I also wanted to confirm that Tracy was correct about the appointments pushing to our calendars. The “meeting topic” automatically gets pushed to our calendar, and we can don’t have to accept the invitation if we don’t want another item on our calendar. However, it is more valuable to have the meeting invite on our calendar than the “meeting topic” that is pushed through because the invite has all of the student information. Is there any way to include all of that information in the item that is pushed to our calendar, or remove the pushed item and only have the calendar invite? We appreciate you looking in to this for us.

**Comment by tdiven** [comment]
This is the iCal and Outlook plugin issue. I will send her an email letting her know we are fixing the iCal invite to not replicate the appt.
