### ISSUE TITLE
Ella Butler Outlook/ConexED Concern

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#297]
Per our meeting with the UofU Career Center on 1/16.

Ella’s using Outlook (web based version on her laptop, as well as desktop version).  When she adds all day events marked as ‘free’ they are blocking the full day in ConexED.  While on campus we asked her to delete the event from her laptop and recreate on her desktop to see if it was something to do with the web version.  The event was recreated on her desktop with the same result.

**Comment by heatherconexed** [comment]
Seth, would you mind reaching out to Ella and see if you are able to resolve?

**Comment by tdiven** [comment]
Seth will contact her today
