### ISSUE TITLE
UofU - more fields pass through from PeopleSoft

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#303]
Per our meeting with the UofU Career Center on 1/16.

They would like to have more fields pass through from PeopleSoft, including Major, Gender, Birthdate, etc. (Allison will send a list of fields wanted).  This will populate on the Appointment Details giving the Advisor more information prior to the meeting, and in the case where a Business Major has scheduled an appointment the Career Center can reach out to the student and cancel/direct them to the proper Dept.

**Comment by mikeg0** [comment]
From Cory ...

This one is likely not possible as it would require an incredible amount of data governance discussion and custom integration with PeopleSoft. we are in a PeopleSoft development freeze for the next 8 months as we go through a  major core upgrade and testing. This information IS available to advisors through our Civitas Inspire for Advisors (IFA) app. I’ll talk internally about the possibility of granting IFA access to Career Coaches. In the future we may want to pursue a strategic partnership with Civitas to add a button to Cranium Cafe that could invoke IFA and query for the student’s dashboard as well as adding a button to IFA that would invoke ConexED Appointment manager and facilitate scheduling an appointment for a student.

**Comment by tdiven** [comment]
Cory said it's not possible.
