### ISSUE TITLE
Make certain reason codes visible

### ISSUE THREAD

**Issue by heatherconexed** [craniumcafe/issue-tracker#316]
UofU feature request.

The ability to make certain reason codes visible, but limit the availability/ability to schedule (i.e. Our resume reviews do not require an appointment and are conducted on a walk-in, first-come, first-served basis. We want students to see resume reviews as a reason code, but if resume review is selected as the reason code, we want students to see a message that indicates “Resume reviews do not require an appointment and are conducted on a walk-in, first-come, first-served basis during Quick Help (Monday-Friday, 8am-5pm)” while not allowing the student to make a resume review appointment.

**Comment by heatherconexed** [comment]
Per Tracy 1/8/18

Gees, this is feature creep. This would be difficult and seriously a one-off. They will need to wait.

**Comment by tdiven** [comment]
They will need to use the function "Only show this Reason Code in the appointment - recorded reason code" and not in the scheduling reason code view.

If this doesn't make sense, let me know.
